name: GitHub environments

on:
  workflow_dispatch:
    
jobs:
  deployment:
    runs-on:  ubuntu-latest

    environment:
      name: production
      url: http://github.com

    steps:
      - name: Print secret from environment
        run: |
          echo APP_SECRET: ${{ secrets.APP_SECRET }}